### ISSUE TITLE
"YAML Media Type" title should use singular

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/mediatypes#44]
This is probably left over from earlier drafts that did cover multiple media types.

**Comment by dret** [comment]
There are a couple more places that use the plural form "media types". Unless I am missing something, these all should be changed to singular form.

**Comment by ioggstream** [comment]
It's `application/yaml` and `+yaml`. I don't have preferences and the singular is OK to me. Feel free to PR :)

**Comment by dret** [comment]
that's what i also thought but then again `+yaml` isn't a media type (as i am sure you know). let's @eemeli be the tie-breaker!

**Comment by eemeli** [comment]
Let's go with the singular form.

**Comment by ioggstream** [comment]
fixed via #45
