### ISSUE TITLE
Clipboard identifiers from YAML

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/mediatypes#66]
From media type ML

## Question

Except being exchanged over http and being edited by simple text-editors (as text), I am supposing that YAML content is likely to be exchanged among editors using a copy-and-paste exchange mechanism. Is it the case?

If this is the case, I would like to suggest to add uniform type identifiers and windows clipboard names so that future implementations may take part to such an exchange in the Additional Information section.

See #1

**Comment by ioggstream** [comment]
@polx can the following values work? I read the wikipedia entry, but is seems a very apple-specific stuff: should they "validate" the value? If we need to add them later, we should be able to do it directly with the IANA, no need to publish a new RFC, right?

@eemeli since you are the  YAML expert, the decision is up to you and the other YAML folks. 

```
Windows Clipboard Name: YAML

Macintosh Universal Type Identifier code: public.yaml
```

**Comment by polx** [comment]
For Windows, I believe this can.

For macOS, I am unfortunately unsure. Although several have defined `public.`-prefixed UTIs, it appears that Apple now considers these UTIs as being those that the OS defines. This was highlighted in [this comment](https://github.com/w3c/clipboard-apis/issues/141#issuecomment-864322885) although it kind of contradicts the history of what was done earlier. That thread has not resolved yet. I would feel that `public.yaml` is good but it would be important to check with some members at Apple to ensure this or simply use `org.yaml`.

**Comment by ioggstream** [comment]
Let's wait for @eemeli .

This should be done in coordination with Apple and MS though. If we don't have connections my suggestion is to defer after the publication.

@darrelmiller can you provide a contact for the windows clipboard identified stuff? Can we use this repo after publication for tracking this kind of activities ?

**Comment by darrelmiller** [comment]
@darrelmiller  I will go hunting.

**Comment by ioggstream** [comment]
@darrelmiller do you think Windows folks will just adapt picking the value we chose? If not, I think that updating the registration afterwards is a sensible choice.

**Comment by polx** [comment]
Here is the documentation bit for windows: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerclipboardformatw

From that page, there seems to be plenty of freedom: either the app chooses something that exists and takes over the same number for its type identifier (they have converged) or they choose to diverge.

I think that those who would adapt if decided now or adapted afterwards are the apps that circulate.

**Comment by darrelmiller** [comment]
I have not got any further information from Microsoft folks, however, what I have seen is that it is it is expected that folks who want to adopt a value are responsible for doing their own due diligence to ensure that the value has not been used for alternative purposes.  I believe that using the YAML clipboard name is a safe choice and that we can close this issue.

**Comment by ioggstream** [comment]
> I believe that using the YAML clipboard name is a safe choice and that we can close this issue

@darrelmiller should we register the YAML clipboard name in the media type registration, then?
