### ISSUE TITLE
Express preference on file extension

### ISSUE THREAD

**Issue by darrelmiller** [ietf-wg-httpapi/mediatypes#68]
Would it be valuable to express a preference for `yaml` over `yml` for file extensions?  I'm assuming 3 character extensions are legacy from DOS file systems that had a 3 character limit.  I reviewed the YAML 1.2 spec and there is no mention of using `yml` as a file extensions, so this might be a good opportunity to steer the community away from having two extensions.

**Comment by handrews** [comment]
Pls let's annihilate the DOS zombie!

**Comment by ioggstream** [comment]
@darrelmiller let's summon  @eemeli and the YAML folks on that. 

IMHO:

-  agree on expressing a preference
- disagree on removing references to .yml, since it's used in the wild.

My2¢, R.

**Comment by ioggstream** [comment]
Discussed with YAML folks. Ok for indicating a preference without normative implications.
