### ISSUE TITLE
AD review

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/mediatypes#73]
- [x] deprecated mediatypes not registered see https://github.com/ietf-wg-httpapi/mediatypes/pull/74

> I would suggest adding some text to clarify these are used but not registered (in accordance with https://www.rfc-editor.org/rfc/rfc6838#section-3.4).

- [x] Section 3.3: "SHOULD only use one extension between yaml and yml"

- > > The simultaneous usage of two filename extensions in the same context might cause interoperability issues (e.g. when both a "config.yaml" and a "config.yml" are present).
>
>  
>
> It feels like the text should end with something like "so only one SHOULD be used.", or anyway give more of a strong recommendation - It just feels like the text is recognizing interoperability issues without providing any response to it.

- [x]  4. ----- FAQ Section:

> I am a bit conflicted about this section. I do like that it provides context around some choices. I understand that it is to be removed before publication, but seeing it there makes me wonder: why have the wg (or the authors) felt the need to add this section? Is this adding some clarification/justification that is missing from the document? In that case, why was the content not included in the text that will be published, rather than exiling it at the end?

FAQ is useful to track closed discussion. Relevant parts have been added to the spec

**Comment by ioggstream** [comment]
@darrelmiller @eemeli Do you think we should use normative language to address the yaml vs yml issue?

**Comment by ioggstream** [comment]
The following statement

> so only one SHOULD be used

could conflict with 

> `.yaml` is preferred.

If we want to use normative language (which we avoided), we can just say `.yaml is RECOMMENDED`.

**Comment by ioggstream** [comment]
@eemeli wdyt on `.yaml` RECOMMENDED?

**Comment by ioggstream** [comment]
The AD proposal is to use normative language @richsalz. If we don't want to do it, I think that the current text is ok.

**Comment by richsalz** [comment]
I do have two concerns:
1. That using normative language here means the whole document needs to be checked for other possible uses.
2. That this then has to go through another WGLC.

**Comment by eemeli** [comment]
I do not have any strong opinions here, and tbh would be fine with any of the options proposed so far. This sounds like a conversation that ought to be happening on a PR.

**Comment by ioggstream** [comment]
@eemeli  if it's ok for you, we can just confirm that we agree to avoid normative statements here, like we decided in #68
