### ISSUE TITLE
Consider removing restated JSON subset requirements.

### ISSUE THREAD

**Issue by sayrer** [ietf-wg-httpapi/mediatypes#87]
I think it might be better to start Section 3.4 with a one sentence paragraph:

```The YAML data model is a superset of that provided by JSON.```

then conclude with the first two existing paragraphs of ```Section 3.4 YAML and JSON```.

The reasoning here is that this document aims not to "imply a specific version", but the JSON mapping could change in the future. This has already happened between the various versions of JSON standards floating around out there.

There is also already a difference between [YAML section 5.2](https://yaml.org/spec/1.2.2/#52-character-encodings) and this document:

```On input, a YAML processor must support the UTF-8 and UTF-16 character encodings. For JSON compatibility, the UTF-32 encodings must also be supported.```

But this document says:

```* non UTF-8 encoding, since YAML supports UTF-16 and UTF-32 in addition to UTF-8;```

You're saying these will cause problems (I agree they probably will...), but the YAML spec says they must be supported _for_ JSON compatibility.

By the way, the most permissive standard, ECMA 404, says only "JSON syntax describes a sequence of Unicode code points." It says that to cover the stuff browsers might put in it, which might almost look like UTF-*, but can contain ill-formed byte-sequences.

**Comment by ioggstream** [comment]
Hi @sayrer, and thanks for your review!

### wrt encoding

A timeline is required here.

- 2006 JSON RFC4627 MAY UTF-32 https://www.rfc-editor.org/rfc/rfc4627#section-6
- 2009 YAML  1.2.1        "must support UTF-32 for JSON compatibility"  [YAML section 5.2](https://yaml.org/spec/1.2.2/#52-character-encodings) and
- 2017 JSON RFC8259 "MUST UTF-8 for interoperability"  https://www.rfc-editor.org/rfc/rfc8259#section-8.1

So, YAML introduced UTF-32 for compatibility with a 2006 JSON specification. This is the reason we suggest UTF-8 for interoperability. 

### wrt ECMA and JSON

I found this mail from Roy Fielding on URI RFC vs WHATWG very interesting in the part where it traces a line between rules to "parse" something, and rules to "interpret" something https://lists.w3.org/Archives/Public/ietf-http-wg/2022AprJun/0173.html

### wrt YAML/JSON superset

still processing ;) I'll comment here.

**Comment by sayrer** [comment]
I think you should revisit this thinking. See [Section 1.2](https://yaml.org/spec/1.2.2/#12-yaml-history) of the YAML spec. It says: "The YAML 1.2 specification was published in 2009. Its primary focus was making YAML a strict superset of JSON."

You are right about what RFC 8259 says, but this is not how JSON actually works. That RFC is a good one to follow if you are being "conservative in what you send", but of course there is the other part of Postel's law here.

**Comment by sayrer** [comment]
Yes, that's a lot better imho.

If a library passes the [JSON Parsing Test Suite](https://github.com/nst/JSONTestSuite) to the extent that it matches the "JavaScript" column, it's accepting invalid UTF-8 in some situations. This is why RFC 8259 mentions the ABNF carve out, and ECMA 404 says only that JSON is "a sequence of Unicode code points" (not characters).
